// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function Authenticate(arg1:boolean):Promise<main.Result>;

export function CancelAuth():Promise<void>;

export function CertDetails():Promise<main.CertDetails>;

export function ExportActiveProfile():Promise<main.Result>;

export function GetConfig():Promise<config.Config>;

export function ImportProfile():Promise<main.Result>;

export function ListRoles():Promise<Array<string>>;

export function RenewToken():Promise<main.Result>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function TokenStatus():Promise<main.Status>;

export function Version():Promise<string>;
