// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['main']['App']['Authenticate'](arg1);
}

export function CancelAuth() {
  return window['go']['main']['App']['CancelAuth']();
}

export function CertDetails() {
  return window['go']['main']['App']['CertDetails']();
}

export function ExportActiveProfile() {
  return window['go']['main']['App']['ExportActiveProfile']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ListRoles() {
  return window['go']['main']['App']['ListRoles']();
}

export function RenewToken() {
  return window['go']['main']['App']['RenewToken']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TokenStatus() {
  return window['go']['main']['App']['TokenStatus']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
